# 自定义配置通过配置中心获取并初始化
server:
  port: 8005

oauth2:
  client:
    id: a1543a1290dbbcd80cfa
    secret: dc5b0bc2706e0c7abd917f596d8d0fb1353002e1
shiro:
  loginUrl: /login

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.206.158:8081
        namespace: 949b591c-dd20-48cf-9032-c5d1e0405577

dubbo:
  registry:
    address: spring-cloud://47.100.206.158:8081
  protocol:
    name: dubbo
    port: -1
  cloud:
    subscribed-services: rio-backend-dev

