spring:
  application:
    name: alibaba-nacos-discovery-server
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.206.158:8081
server:
  port: 8001


# dubbo 配置
dubbo:
  scan:
    base-packages: com.nacos.demo.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services:

